---
driver:
  # using docker to test
  name: docker
  instance_name: test
  use_sudo: false
  privileged: true
  remove_images: true

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
  # list of ansible galaxy requirements from the roles meta/main.yml
  requirements_path: requirements.yml

verifier:
  name: inspec
  
platforms:
  - name: ubuntu-14.04

suites:
  # suites found at /test/integration/$test-name
  - name: default
